### ISSUE TITLE
Server only version?

### ISSUE THREAD

**Issue by Sir-Will** [Barteks2x/FastFlyBlockBreaking#3]
hey,

Is it not possible to get this working with only having the mod on the server and not on the client?

**Comment by Niko-sk2x** [comment]
No, it's not possible. While the server does control block breaking timing, it doesn't have much control over the block breaking animation.

If you recompiled the mod with a little change in `@Mod` to allow it being only on the server, it would probably work as server-only mod, but the effect would be that the block disappears in the middle of the normal, slow speed breaking.
