### ISSUE TITLE
this really weird problem.

### ISSUE THREAD

**Issue by Dasteveq** [Barteks2x/FastFlyBlockBreaking#4]
oki so i installed this mod with morph mod being my 'way' of flying.
i noticed that with this mod is still really slow to break blocks as a bat flying...

i thought at first that maybe tools aren't supported or something (i used TC tools) but even with bare hands is still very slow breaking wood planks compared to me not flying.

i really think this mistake shouldn't happen so i assume that this mod isn't what i expected maybe? or it's disabled by default...

i really need confirmation, sincerely thanks for reading.

*edit: I use the latest version of this in 1.7.10*

**Comment by Niko-sk2x** [comment]
I don't see why it wouldn't work, can you upload the log?

You can also try to set config option `alwaysFastBreaking` to true and see if that fixes it.

**Comment by Dasteveq** [comment]
umm i tried to turn it true from false but that didn't work sadly...

for confirmation purposes, i tried to remove the other mods and keep morph and FFBB only and tbh it worked. 

i also tried to clean my Minecraft folder but the problem still exists...

so probably one of the mods causing it to stop and idk which one...

[this log file.log](https://github.com/Barteks2x/FastFlyBlockBreaking/files/3427532/this.log.file.log)

*log before clearing folder*

[latest.log](https://github.com/Barteks2x/FastFlyBlockBreaking/files/3427537/latest.log)

*log after clearing folder*

[the mods.txt](https://github.com/Barteks2x/FastFlyBlockBreaking/files/3427574/the.mods.txt)

*mods list*

**Comment by Niko-sk2x** [comment]
I don't see anything wrong in the log, but can you upload fml-latest-client or debug.log?

The only way I can see it not working is that the event isn't being fired.

**Comment by Niko-sk2x** [comment]
I was able to reproduce the issue some some of the mods you have. Now trying to find which mod caused it.

**Comment by Niko-sk2x** [comment]
Aether 2 is incompatible. 1.7.10 version of the code is not available so I can't really determine what is the reason.
